//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Cliente.serviciosw {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioWebSoap", Namespace="http://localhost/webService")]
    public partial class ServicioWeb : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback horayfechaOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertarespejoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarArbolOperationCompleted;
        
        private System.Threading.SendOrPostCallback matricesOperationCompleted;
        
        private System.Threading.SendOrPostCallback leercsvUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback leercsvJuegos_usuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback leercsvTableroOperationCompleted;
        
        private System.Threading.SendOrPostCallback leerJuegoActualOperationCompleted;
        
        private System.Threading.SendOrPostCallback Reportede0OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioWeb() {
            this.Url = global::Cliente.Properties.Settings.Default.Cliente_localhost_ServicioWeb;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event horayfechaCompletedEventHandler horayfechaCompleted;
        
        /// <remarks/>
        public event insertarespejoCompletedEventHandler insertarespejoCompleted;
        
        /// <remarks/>
        public event InsertarArbolCompletedEventHandler InsertarArbolCompleted;
        
        /// <remarks/>
        public event matricesCompletedEventHandler matricesCompleted;
        
        /// <remarks/>
        public event leercsvUsuariosCompletedEventHandler leercsvUsuariosCompleted;
        
        /// <remarks/>
        public event leercsvJuegos_usuariosCompletedEventHandler leercsvJuegos_usuariosCompleted;
        
        /// <remarks/>
        public event leercsvTableroCompletedEventHandler leercsvTableroCompleted;
        
        /// <remarks/>
        public event leerJuegoActualCompletedEventHandler leerJuegoActualCompleted;
        
        /// <remarks/>
        public event Reportede0CompletedEventHandler Reportede0Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/webService/HelloWorld", RequestNamespace="http://localhost/webService", ResponseNamespace="http://localhost/webService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/webService/horayfecha", RequestNamespace="http://localhost/webService", ResponseNamespace="http://localhost/webService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string horayfecha() {
            object[] results = this.Invoke("horayfecha", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void horayfechaAsync() {
            this.horayfechaAsync(null);
        }
        
        /// <remarks/>
        public void horayfechaAsync(object userState) {
            if ((this.horayfechaOperationCompleted == null)) {
                this.horayfechaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhorayfechaOperationCompleted);
            }
            this.InvokeAsync("horayfecha", new object[0], this.horayfechaOperationCompleted, userState);
        }
        
        private void OnhorayfechaOperationCompleted(object arg) {
            if ((this.horayfechaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.horayfechaCompleted(this, new horayfechaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/webService/insertarespejo", RequestNamespace="http://localhost/webService", ResponseNamespace="http://localhost/webService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string insertarespejo() {
            object[] results = this.Invoke("insertarespejo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void insertarespejoAsync() {
            this.insertarespejoAsync(null);
        }
        
        /// <remarks/>
        public void insertarespejoAsync(object userState) {
            if ((this.insertarespejoOperationCompleted == null)) {
                this.insertarespejoOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertarespejoOperationCompleted);
            }
            this.InvokeAsync("insertarespejo", new object[0], this.insertarespejoOperationCompleted, userState);
        }
        
        private void OninsertarespejoOperationCompleted(object arg) {
            if ((this.insertarespejoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertarespejoCompleted(this, new insertarespejoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/webService/InsertarArbol", RequestNamespace="http://localhost/webService", ResponseNamespace="http://localhost/webService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertarArbol() {
            object[] results = this.Invoke("InsertarArbol", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertarArbolAsync() {
            this.InsertarArbolAsync(null);
        }
        
        /// <remarks/>
        public void InsertarArbolAsync(object userState) {
            if ((this.InsertarArbolOperationCompleted == null)) {
                this.InsertarArbolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarArbolOperationCompleted);
            }
            this.InvokeAsync("InsertarArbol", new object[0], this.InsertarArbolOperationCompleted, userState);
        }
        
        private void OnInsertarArbolOperationCompleted(object arg) {
            if ((this.InsertarArbolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarArbolCompleted(this, new InsertarArbolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/webService/matrices", RequestNamespace="http://localhost/webService", ResponseNamespace="http://localhost/webService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string matrices() {
            object[] results = this.Invoke("matrices", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void matricesAsync() {
            this.matricesAsync(null);
        }
        
        /// <remarks/>
        public void matricesAsync(object userState) {
            if ((this.matricesOperationCompleted == null)) {
                this.matricesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmatricesOperationCompleted);
            }
            this.InvokeAsync("matrices", new object[0], this.matricesOperationCompleted, userState);
        }
        
        private void OnmatricesOperationCompleted(object arg) {
            if ((this.matricesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.matricesCompleted(this, new matricesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/webService/leercsvUsuarios", RequestNamespace="http://localhost/webService", ResponseNamespace="http://localhost/webService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string leercsvUsuarios() {
            object[] results = this.Invoke("leercsvUsuarios", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void leercsvUsuariosAsync() {
            this.leercsvUsuariosAsync(null);
        }
        
        /// <remarks/>
        public void leercsvUsuariosAsync(object userState) {
            if ((this.leercsvUsuariosOperationCompleted == null)) {
                this.leercsvUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnleercsvUsuariosOperationCompleted);
            }
            this.InvokeAsync("leercsvUsuarios", new object[0], this.leercsvUsuariosOperationCompleted, userState);
        }
        
        private void OnleercsvUsuariosOperationCompleted(object arg) {
            if ((this.leercsvUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.leercsvUsuariosCompleted(this, new leercsvUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/webService/leercsvJuegos_usuarios", RequestNamespace="http://localhost/webService", ResponseNamespace="http://localhost/webService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string leercsvJuegos_usuarios() {
            object[] results = this.Invoke("leercsvJuegos_usuarios", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void leercsvJuegos_usuariosAsync() {
            this.leercsvJuegos_usuariosAsync(null);
        }
        
        /// <remarks/>
        public void leercsvJuegos_usuariosAsync(object userState) {
            if ((this.leercsvJuegos_usuariosOperationCompleted == null)) {
                this.leercsvJuegos_usuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnleercsvJuegos_usuariosOperationCompleted);
            }
            this.InvokeAsync("leercsvJuegos_usuarios", new object[0], this.leercsvJuegos_usuariosOperationCompleted, userState);
        }
        
        private void OnleercsvJuegos_usuariosOperationCompleted(object arg) {
            if ((this.leercsvJuegos_usuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.leercsvJuegos_usuariosCompleted(this, new leercsvJuegos_usuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/webService/leercsvTablero", RequestNamespace="http://localhost/webService", ResponseNamespace="http://localhost/webService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string leercsvTablero() {
            object[] results = this.Invoke("leercsvTablero", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void leercsvTableroAsync() {
            this.leercsvTableroAsync(null);
        }
        
        /// <remarks/>
        public void leercsvTableroAsync(object userState) {
            if ((this.leercsvTableroOperationCompleted == null)) {
                this.leercsvTableroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnleercsvTableroOperationCompleted);
            }
            this.InvokeAsync("leercsvTablero", new object[0], this.leercsvTableroOperationCompleted, userState);
        }
        
        private void OnleercsvTableroOperationCompleted(object arg) {
            if ((this.leercsvTableroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.leercsvTableroCompleted(this, new leercsvTableroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/webService/leerJuegoActual", RequestNamespace="http://localhost/webService", ResponseNamespace="http://localhost/webService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string leerJuegoActual() {
            object[] results = this.Invoke("leerJuegoActual", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void leerJuegoActualAsync() {
            this.leerJuegoActualAsync(null);
        }
        
        /// <remarks/>
        public void leerJuegoActualAsync(object userState) {
            if ((this.leerJuegoActualOperationCompleted == null)) {
                this.leerJuegoActualOperationCompleted = new System.Threading.SendOrPostCallback(this.OnleerJuegoActualOperationCompleted);
            }
            this.InvokeAsync("leerJuegoActual", new object[0], this.leerJuegoActualOperationCompleted, userState);
        }
        
        private void OnleerJuegoActualOperationCompleted(object arg) {
            if ((this.leerJuegoActualCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.leerJuegoActualCompleted(this, new leerJuegoActualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/webService/Reportede0", RequestNamespace="http://localhost/webService", ResponseNamespace="http://localhost/webService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Reportede0() {
            object[] results = this.Invoke("Reportede0", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Reportede0Async() {
            this.Reportede0Async(null);
        }
        
        /// <remarks/>
        public void Reportede0Async(object userState) {
            if ((this.Reportede0OperationCompleted == null)) {
                this.Reportede0OperationCompleted = new System.Threading.SendOrPostCallback(this.OnReportede0OperationCompleted);
            }
            this.InvokeAsync("Reportede0", new object[0], this.Reportede0OperationCompleted, userState);
        }
        
        private void OnReportede0OperationCompleted(object arg) {
            if ((this.Reportede0Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Reportede0Completed(this, new Reportede0CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void horayfechaCompletedEventHandler(object sender, horayfechaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class horayfechaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal horayfechaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void insertarespejoCompletedEventHandler(object sender, insertarespejoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertarespejoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertarespejoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void InsertarArbolCompletedEventHandler(object sender, InsertarArbolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertarArbolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertarArbolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void matricesCompletedEventHandler(object sender, matricesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class matricesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal matricesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void leercsvUsuariosCompletedEventHandler(object sender, leercsvUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class leercsvUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal leercsvUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void leercsvJuegos_usuariosCompletedEventHandler(object sender, leercsvJuegos_usuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class leercsvJuegos_usuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal leercsvJuegos_usuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void leercsvTableroCompletedEventHandler(object sender, leercsvTableroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class leercsvTableroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal leercsvTableroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void leerJuegoActualCompletedEventHandler(object sender, leerJuegoActualCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class leerJuegoActualCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal leerJuegoActualCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Reportede0CompletedEventHandler(object sender, Reportede0CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Reportede0CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Reportede0CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591